/**
 * generated by Xtext 2.10.0
 */
package com.zenika;

import com.zenika.AbstractAicdslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class AicdslRuntimeModule extends AbstractAicdslRuntimeModule {
}
