/**
 * generated by Xtext 2.10.0
 */
package com.zenika;

import com.zenika.AicdslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AicdslStandaloneSetup extends AicdslStandaloneSetupGenerated {
  public static void doSetup() {
    AicdslStandaloneSetup _aicdslStandaloneSetup = new AicdslStandaloneSetup();
    _aicdslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
