/**
 * generated by Xtext 2.10.0
 */
package com.zenika.validation;

import com.zenika.validation.AbstractAicdslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class AicdslValidator extends AbstractAicdslValidator {
}
