/*
 * generated by Xtext 2.10.0
 */
package com.zenika


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AicdslStandaloneSetup extends AicdslStandaloneSetupGenerated {

	def static void doSetup() {
		new AicdslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
