/*
 * generated by Xtext 2.10.0
 */
package com.zenika.idea.lang


class AicdslFileType extends AbstractAicdslFileType {
	public static final AicdslFileType INSTANCE = new AicdslFileType()
	
	new() {
		super(AicdslLanguage.INSTANCE)
	}
}
