/*
 * generated by Xtext 2.10.0
 */
package com.zenika.idea.completion

import com.zenika.idea.lang.AicdslLanguage
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage

class AicdslCompletionContributor extends AbstractAicdslCompletionContributor {
	new() {
		this(AicdslLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
