/*
 * generated by Xtext 2.10.0
 */
package com.zenika.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class AicdslIdeaModule extends AbstractAicdslIdeaModule {
}
