/*
 * generated by Xtext 2.10.0
 */
package com.zenika.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class AicdslIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new AicdslStandaloneSetupIdea().createInjector
	}

}
